# Generated by Django 5.2.7 on 2026-06-10 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooksmodel',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Science', 'Science'), ('Technology', 'Technology'), ('Novel', 'Novel'), ('Other', 'Other')], max_length=80),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
    ]
