# Generated by Django 5.2.7 on 2026-06-10 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0002_remove_ebooksmodel_author_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EBooksModel',
            new_name='EBook',
        ),
    ]
