# Generated by Django 5.2.7 on 2026-06-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0003_rename_ebooksmodel_ebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Fiction', 'Fiction'), ('Science', 'Science')], max_length=50),
        ),
    ]
