# Generated by Django 5.2.7 on 2026-06-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0004_alter_ebook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Fiction', 'Fiction'), ('Science', 'Science')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
